---
openapi: 3.0.1
info:
  title: DateApi for Applicant Kata
  version: v1.0
servers:
  - url:  http://localhost:8080/Api/v2
paths:
  /PublicHolidays/{year}/{countrycode}:
    get:
      tags:
      - Api
      parameters:
      - examples:
          Year:
            value: "2023"
        name: year
        description: ""
        schema:
          format: int32
          description: ""
          type: integer
        in: path
        required: true
      - examples:
          CountryCode:
            value: JM
        name: countrycode
        description: ISO 3166 Alpha 2 Countrycode. (2 Letters)
        schema:
          description: ""
          type: string
        in: path
        required: true
      responses:
        "200":
          content:
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicHolidayDto'
              examples:
                Example Response for 2021:
                  value:
                  - date: 2021-03-08
                    localName: Internationaler Frauentag
                    name: International Women's Day
                    countryCode: DE
                    fixed: true
                    global: false
                    counties:
                    - DE-BE
                    launchYear: 2019
                    type: Public
                  - date: 2021-06-03
                    localName: Fronleichnam
                    name: Corpus Christi
                    countryCode: DE
                    fixed: false
                    global: false
                    counties:
                    - DE-BW
                    - DE-BY
                    - DE-HE
                    - DE-NW
                    - DE-RP
                    - DE-SL
                    type: Public
          description: Success
      summary: Get Public Holiday
components:
  schemas:
    PublicHolidayType:
      description: Contains the type (if existing) of the Holiday
      enum:
      - Public
      - Bank
      - School
      - Authorities
      - Optional
      - Observance
      type: string
      example: '"Optional"'
    PublicHolidayDto:
      type: object
      properties:
        date:
          format: date
          description: The date
          type: string
        localName:
          nullable: true
          description: Local name
          type: string
        name:
          nullable: true
          description: English name
          type: string
        countryCode:
          nullable: true
          description: ISO 3166-1 alpha-2
          type: string
        fixed:
          description: Is this public holiday every year on the same date
          type: boolean
        global:
          description: Is this public holiday in every county (federal state)
          type: boolean
        counties:
          nullable: true
          description: ISO-3166-2 - Federal states - Used if the holiday applies only
            to specific federal states.
          type: array
          items:
            type: string
        launchYear:
          nullable: true
          format: int32
          description: The launch year of the public holiday
          type: integer
        type:
          $ref: '#/components/schemas/PublicHolidayType'
      additionalProperties: false
      example:
        date: 2021-03-08
        localName: Internationaler Frauentag
        name: International Women's Day
        countryCode: DE
        fixed: true
        global: false
        counties:
        - DE-BE
        launchYear: 2019
        type: Public
    CountryInfoDto:
      type: object
      properties:
        commonName:
          nullable: true
          type: string
        officialName:
          nullable: true
          type: string
        countryCode:
          nullable: true
          type: string
        region:
          nullable: true
          type: string
      additionalProperties: false
      example: "{\n    \"commonName\": \"United States\",\n    \"officialName\": \"\
        United States of America\",\n    \"countryCode\": \"US\",\n    \"region\"\
        : \"Americas\",\n}"
